# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 1908703d23d1cece579c3e5579779b57f135257d5e615ce082b213238dfdb1af
    docker:
      # specify the version you desire here
      - image: circleci/node:10.13.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/bill-pay

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - type: cache-restore
        name: Restore Code Climate cache
        key: v1-code-climate-0.1.4
      - run:
          name: Install Code Climate reporter
          command: |
            if [[ ! -x cc-test-reporter ]]
            then
              curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.1.4-linux-amd64 > ./cc-test-reporter
              chmod +x ./cc-test-reporter
            fi
      - type: cache-save
        name: Save Code Climate cache
        key: v1-code-climate-0.1.4
        paths:
          - ./cc-test-reporter

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: "Run node test and Collect Coverage Reports"
          command: yarn cover

      - run:
          name: Report code coverage from circleCI to Code Climate
          command: |
            ./cc-test-reporter format-coverage -t lcov -o "coverage/codeclimate.$CIRCLE_NODE_INDEX.json"
